DROP TABLE IF EXISTS dim_patient;
CREATE TABLE dim_patient (
  patient_ref_key int GENERATED BY DEFAULT AS IDENTITY (1,1),
  patient_id varchar,
  name_prefix varchar,
  first_name varchar,
  last_name varchar,
  patient_full_name varchar,
  date_of_birth varchar,
  phone_number varchar,
  email_id varchar,
  effective_start_date timestamp DEFAULT getdate(),
  effective_end_date timestamp DEFAULT NULL,
  is_current char(1) DEFAULT 'Y'
);

DROP TABLE IF EXISTS dim_date;
CREATE TABLE dim_date (
  date_id int GENERATED BY DEFAULT AS IDENTITY (1,1),
  full_date varchar,
  year varchar,
  month varchar,
  day varchar,
  week varchar,
  quarter varchar
);

DROP TABLE IF EXISTS dim_policy;
CREATE TABLE dim_policy (
  policy_ref_key int GENERATED BY DEFAULT AS IDENTITY (1,1),
  policy_id varchar,
  policy_start_date varchar,
  policy_end_date varchar,
  premium_amount varchar,
  coverage_limit varchar,
  effective_start_date timestamp DEFAULT getdate(),
  effective_end_date timestamp DEFAULT NULL,
  is_current char(1) DEFAULT 'Y'
);

DROP TABLE IF EXISTS dim_address;
CREATE TABLE dim_address (
  address_ref_key int GENERATED BY DEFAULT AS IDENTITY (1,1),
  address_id varchar,
  addressline varchar,
  borough varchar,
  borough_level varchar,
  borough_latitude varchar,
  borough_longitude varchar,
  borough_abbrev varchar,
  borough_code varchar,
  city varchar,
  state varchar,
  effective_start_date timestamp DEFAULT getdate(),
  effective_end_date timestamp DEFAULT NULL,
  is_current char(1) DEFAULT 'Y'
);

DROP TABLE IF EXISTS dim_claims;
CREATE TABLE dim_claims (
  claim_ref_key int GENERATED BY DEFAULT AS IDENTITY (1,1),
  claim_id varchar,
  high_risk_claim_flag  varchar,
  claim_initialized_date varchar,
  claim_request_amount varchar,
  claim_status varchar,
  claim_rejected_reason varchar
);

DROP TABLE IF EXISTS fact_claims_hist;
CREATE TABLE fact_claims_hist (
  fact_claim_id int GENERATED BY DEFAULT AS IDENTITY (1,1),
  patient_ref_key int,
  claim_ref_key int,
  address_ref_key int,
  policy_ref_key int,
  last_updated_date datetime
);
